/**
 * 脚手架 package.json 配置
 */
module.exports = {
  "name": "",
  "version": "",
  "description": "",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cz": "git cz",
    "eslint": "eslint --fix ./src --ext .ts,.tsx,.js",
    "changelog": "conventional-changelog -p angular -i CHANGELOG.md -s -r 0",
    "dll": "webpack --config ./build-config/webpack.dll.config.js",
    "start": "npm run dev:com",
    "build": "npm run build:com",
    "dev": "node ./build-config/common/dev.js",
    "build": "node ./build-config/common/prod.js"
  },
  "keywords": [
    "docker",
    "webpack",
    "react",
    "typescript",
    "babel",
    "eslint",
    "less"
  ],
  "author": "",
  "devDependencies": {
    "@babel/cli": "^7.12.1",
    "@babel/core": "^7.12.3",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-proposal-decorators": "^7.12.1",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
    "@babel/preset-typescript": "^7.12.1",
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "@types/react": "^16.9.53",
    "@types/react-dom": "^16.9.8",
    "@types/react-redux": "^7.1.9",
    "@types/react-router-dom": "^5.1.6",
    "@types/redux-logger": "^3.0.8",
    "@typescript-eslint/eslint-plugin": "^4.5.0",
    "@typescript-eslint/parser": "^4.5.0",
    "antd-dayjs-webpack-plugin": "^1.0.1",
    "autoprefixer": "^10.0.1",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-import": "^1.13.1",
    "clean-webpack-plugin": "^3.0.0",
    "commitizen": "^4.2.2",
    "commitlint": "^11.0.0",
    "conventional-changelog-cli": "^2.1.0",
    "copy-webpack-plugin": "^6.2.1",
    "css-loader": "^5.0.0",
    "cssnano": "^4.1.10",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^7.11.0",
    "eslint-config-prettier": "^6.14.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.21.5",
    "express": "^4.17.1",
    "file-loader": "^6.1.1",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "hard-source-webpack-plugin": "^0.13.1",
    "html-webpack-plugin": "^4.5.0",
    "html-webpack-tags-plugin": "^2.0.17",
    "http-proxy-middleware": "^1.0.6",
    "husky": "^4.3.0",
    "less": "^3.12.2",
    "less-loader": "^7.0.2",
    "mini-css-extract-plugin": "^1.1.2",
    "optimize-css-assets-webpack-plugin": "^5.0.4",
    "postcss": "^8.1.3",
    "postcss-import": "^13.0.0",
    "postcss-loader": "^4.0.4",
    "prettier": "^2.1.2",
    "raw-loader": "^4.0.2",
    "regenerator-runtime": "^0.13.7",
    "speed-measure-webpack-plugin": "^1.3.3",
    "style-loader": "^2.0.0",
    "terser-webpack-plugin": "^5.0.0",
    "thread-loader": "^3.0.0",
    "typescript": "^4.0.3",
    "url-loader": "^4.1.1",
    "webpack": "^4.43.0",
    "webpack-bundle-analyzer": "^3.9.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-middleware": "^3.7.2",
    "webpack-hot-middleware": "^2.25.0",
    "webpack-merge": "^5.2.0"
  },
  "dependencies": {
    "antd": "^4.7.2",
    "core-js": "^3.6.5",
    "crypto-js": "^4.0.0",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-redux": "^7.2.1",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "browserslist": [
    "> 0.5%",
    "last 3 version",
    "ie 11"
  ]
}; 